### ISSUE TITLE
False positive build by maven

### ISSUE THREAD

**Issue by wjkveen** [msoute/vertx-deploy-tools#10]
A deploy by Jenkins with maven, using the vertx-deploy-tools with the Jenkins plugin, failed undetectedly.  Maven claimed that the deploy finished successfully, but it failed to pick up an earlier error indicated in the Jenkins log. See also attached excerpt of the log file:

{code}
[INFO] Waiting for deploy to finish. Current status : Deploy in state : WAITING_FOR_REGISTER
[INFO] Waiting for deploy to finish. Current status : Deploy in state : WAITING_FOR_REGISTER
[INFO] Waiting for deploy to finish. Current status : Deploy in state : WAITING_FOR_REGISTER
[INFO] Waiting for deploy to finish. Current status : Deploy in state : WAITING_FOR_REGISTER
[ERROR] Deploy request failed
[INFO] Shutting down executor
[INFO] awaiting termination of executor
[INFO] Updates state for instance i-9d907125 to UNKNOWN
[INFO] Set minimal capacity for group to 0
[INFO] Resumed auto scaling processes.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:58 min
[INFO] Finished at: 2015-09-25T07:10:01+00:00
[INFO] Final Memory: 12M/149M
[INFO] ------------------------------------------------------------------------
Vertx deploy completed: SUCCESS
Build step 'Execute Vert.X Deploy' changed build result to SUCCESS
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Notifying upstream projects of job completion
Finished: SUCCESS
{code}

**Comment by msoute** [comment]
@wjkveen what deploy strategy was used ?

**Comment by msoute** [comment]
Never mind. Log stated WHATEVER strategy has been used
It defaults to this strategy if no instances are InService. This causes the build not to fail
