### ISSUE TITLE
kill hanging vert.x modules when gracefully stopping is unsuccessful

### ISSUE THREAD

**Issue by henrybravo** [msoute/vertx-deploy-tools#16]
If a vertical was unable to be stopped in nl.jpoint.vertx.mod.cluster.command.StopModule.java then it can be killed with e.g. "killProcess = Runtime.getRuntime().exec(new String[]{"sudo", "/etc/init.d/vertx", "stop"});"
The vert.x init script was enhanced with a "hard_kill" function (at Malmberg) which kills (-9) remaining verticals.

**Comment by msoute** [comment]
Fixed in new init.d scripts
