### ISSUE TITLE
Service-specific config files with module ids with a colon are invalid filenames in Windows

### ISSUE THREAD

**Issue by bertjan** [msoute/vertx-deploy-tools#34]
The deploy-tools allow for service-specific configuration using a config file with a name equal to the module id (groupid:artifactid).
Filenames with a colon are not supported on Windows.
The previous (vertx2) format with a ~ as group/artifact separator did work on windows.

**Comment by MarcelTon** [comment]
Do want :+1:

**Comment by msoute** [comment]
#43
