### ISSUE TITLE
Add "deploy.as.test" as startup parameter 

### ISSUE THREAD

**Issue by paulmiddelkoop** [msoute/vertx-deploy-tools#36]
Please add "deploy.as.test" as JVM parameter when starting verticles. That way we can bundle all verticles in one starter verticle and filter out test verticles in this starter verticle.

By the way: rename DeployUtils.FilterTestArtifacts to DeployUtils.filterTestArtifacts()?

**Comment by msoute** [comment]
#37

**Comment by msoute** [comment]
Merged
