### ISSUE TITLE
vertxdeploy.scope.test always false after rotate

### ISSUE THREAD

**Issue by paulmiddelkoop** [msoute/vertx-deploy-tools#38]
When deploying using deploy.as.test=true, the application will not start up correctly after a rotate. The ELB has correct information: deploy.as.test=true, but the application is started with -Dvertxdeploy.scope.test=false.

**Comment by msoute** [comment]
@paulmiddelkoop please test latest 3.1.0-SNAPSHOT

**Comment by paulmiddelkoop** [comment]
Works correctly now. Thanks for the quick fix.

**Comment by msoute** [comment]
merged in master
