### ISSUE TITLE
Support for .tar.gz files

### ISSUE THREAD

**Issue by jvwilge** [msoute/vertx-deploy-tools#56]
When using symlinks the `maven-assembly-plugin` produces these files as empty files in the resulting .zip .
This problem does not occur on .tar.gz files

Reproducible by creating a .txt file, a symlink to this file and running `mvn package` on the attached project files (rename files to .xml)

[assembly.txt](https://github.com/msoute/vertx-deploy-tools/files/1397861/assembly.txt)
[pom.txt](https://github.com/msoute/vertx-deploy-tools/files/1397862/pom.txt)

**Comment by msoute** [comment]
Since 3.2.4
